name: AutoUUPBuild

on:
    workflow_dispatch:  # 手动触发工作流

jobs:
  build:
    runs-on: windows-latest  # 运行环境可以是ubuntu, windows, 或 macos

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'  # 设置你使用的Python版本

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 获取最新的 UUP 下载包，并解压到当前目录
      - name: Get latest UUP download package
        run: |
          python down.py

      # 自定义参数
      - name: Customize parameters
        run: |
          python reCC_3wim.py
          python reCAL.py

      - name: Read version file
        id: read_version
        run: |
          # Check if the version file exists
          if (-Not (Test-Path -Path "version")) {
            echo "Error: version file not found."
            exit 1
          }

          # Read the version file
          $version = Get-Content -Path "version"

          # Export the version as an environment variable
          echo "VERSION=$version" >> $env:GITHUB_ENV

      - name: Use version variable
        run: |
          echo "The version is: $env:VERSION"

      # 执行uup_download_windows.cmd
      - name: Run uup_download_windows.cmd
        shell: cmd
        run: |
          uup_download_windows.cmd  # 执行uup_download_windows.cmd脚本

      - name: Rename install.wim
        run: |
          # Check if install.wim exists
          if (Test-Path -Path "install.wim") {
            # Rename install.wim to env.version.wim
            $newFileName = "$($env:VERSION)_3.wim"
            Rename-Item -Path "install.wim" -NewName $newFileName
            echo "install.wim has been renamed to $newFileName"
          } else {
            echo "install.wim not found."
          }

      - name: Upload Build Artifacts (WIM)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.VERSION }}
          path: |
            ${{ env.VERSION }}_3.wim

      - name: Check if tag exists and get existing release
        id: check_tag
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: process.env.VERSION
            }).catch(() => null);
            core.setOutput('tag_exists', release ? true : false);
            if (release) {
              core.setOutput('upload_url', release.data.upload_url);
              core.setOutput('release_id', release.data.id);
            }

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          draft: false
          prerelease: false
        if: ${{ !steps.check_tag.outputs.tag_exists }}

      - name: Upload Build Artifacts (WIM)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.check_tag.outputs.tag_exists ? steps.check_tag.outputs.upload_url : steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.VERSION }}_3.wim
          asset_name: ${{ env.VERSION }}_3.wim
          asset_content_type: application/octet-stream