name: Build By Bat

on:
    workflow_dispatch:  # 手动触发工作流

jobs:
  build:
    runs-on: windows-latest  # 运行环境可以是ubuntu, windows, 或 macos

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'  # 设置你使用的Python版本

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 获取最新的 UUP 下载包，并解压到当前目录
      - name: Get latest UUP download package
        run: |
          python down.py

      # 自定义参数
      - name: Customize parameters
        run: |
          python reCC.py
          python reCAL.py

      - name: Read version file
        id: read_version
        run: |
          # Check if the version file exists
          if (-Not (Test-Path -Path "version")) {
            echo "Error: version file not found."
            exit 1
          }

          # Read the version file
          $version = Get-Content -Path "version"

          # Export the version as an environment variable
          echo "VERSION=$version" >> $env:GITHUB_ENV

      - name: Use version variable
        run: |
          echo "The version is: $env:VERSION"

      # 执行uup_download_windows.cmd
      - name: Run uup_download_windows.cmd
        shell: cmd
        run: |
          uup_download_windows.cmd  # 执行uup_download_windows.cmd脚本

      - name: Find ISO file
        id: find_iso
        run: |
          # Find the ISO file in the current directory
          $isoFile = Get-ChildItem -Path . -Filter *.iso | Select-Object -First 1
          if ($isoFile) {
            echo "ISO_FILE=$isoFile.FullName" >> $env:GITHUB_ENV
            echo "ISO_FILE_NAME=$isoFile.Name" >> $env:GITHUB_ENV
          } else {
            echo "Error: ISO file not found."
            exit 1
          }

      - name: Upload Build Artifacts (ISO)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.VERSION }}
          path: |
            ${{ env.ISO_FILE }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Build Artifacts (ISO)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ISO_FILE }}
          asset_name: ${{ env.VERSION }}.iso
          asset_content_type: application/octet-stream